### ISSUE TITLE
mix ecto.migrate fail

### ISSUE THREAD

**Issue by denegny** [maratgaliev/erlangjobs#15]
Hi
Try install app and get this error ((

`18:38:45.941 [debug] QUERY ERROR source="jobs" db=14.0ms
SELECT j0."id", j0."title", j0."description", j0."city", j0."is_remote", j0."is_approved", j0."salary", j0."email", j0."company", j0."site", j0."phone", j0."contact_name", j0."currency_type", j0."employment_type", j0."slug", j0."inserted_at", j0."updated_at" FROM "jobs" AS j0 []
** (Postgrex.Error) ERROR 42703 (undefined_column): column j0.is_approved does not exist`

**Comment by maratgaliev** [comment]
Looks like migrations order error. If you want, you can fix it or wait some time, when it will be fixed by developers :)

**Comment by denegny** [comment]
Yes, all right, I saw))
