### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by denegny** [maratgaliev/erlangjobs#16]
Please fix the error in the installation instructions for node

  * Install latest Elixir & Phoenix
  * Install dependencies with `mix deps.get`
  * Create and migrate your database with `mix ecto.create && mix ecto.migrate`
  * Install Node.js dependencies with `cd assets && npm install && cd ..`
  * Start Phoenix endpoint with `mix phx.server`

**Comment by denegny** [comment]
for more comfortable setup, add this code in `mix.exs` 

```elixir
  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
```

**Comment by Nitrino** [comment]
@denegny This code is automatically generated and already exists in the mix.exs
