### ISSUE TITLE
premoderation of publications

### ISSUE THREAD

**Issue by Nitrino** [maratgaliev/erlangjobs#4]
I saw in the rss feed the following entry: "Помощь в оформлении физическим лицам и сотрудникам учереждений карт metro в сеть немецких супермаркетов МETRO CASH & CARRY.
Erlang and Elixir jobs"

@maratgaliev what do you think about adding premoderation publications?

**Comment by maratgaliev** [comment]
Yep, I saw it and deleted this entry. And this is good idea. If you want, you can implement it. It will be great.

**Comment by Nitrino** [comment]
ok, I'll do it

**Comment by Nitrino** [comment]
Already implemented
